import { AgeRating } from "./AgeRating";
import { GenreTheme } from "./GenreTheme";
import { Platform } from "./Platform";
import { Image } from "./Image";
import { Video } from "./Video";
import { Franchise } from "./Franchise";
import { Series } from "./Series";
import { Website } from "./Website";
import { AlternativeName } from "./AlternativeName";
import { InvolvedCompany } from "./InvolvedCompany";
import { GameMode } from "./GameMode";
import { PlayerPerspective } from "./PlayerPerspective";

export type Game = {
  id: number;
  aggregated_rating?: number;
  aggregated_rating_count?: number;
  name?: string;
  slug?: string;
  summary?: string;
  first_release_date?: number;
  cover?: Image;
  player_perspectives?: PlayerPerspective[];
  game_modes?: GameMode[];
  alternative_names?: AlternativeName[];
  involved_companies?: InvolvedCompany[];
  age_ratings?: AgeRating[];
  genres?: GenreTheme[];
  themes?: GenreTheme[];
  platforms?: Platform[];
  screenshots?: Image[];
  artworks?: Image[];
  videos?: Video[];
  parent_game?: Game;
  franchises?: Franchise[];
  collection?: Series;
  remakes?: Game[];
  remasters?: Game[];
  expanded_games?: Game[];
  standalone_expansions?: Game[];
  expansions?: Game[];
  websites?: Website[];
};
